### ISSUE TITLE
Implementovat Ansible AWX pro automatizaci vzdálené storage.

### ISSUE THREAD

**Issue by hates52** [Cloud-for-You/storage-operator#56]
Pri rekoncilaci PVC bude mít možnost volat REST API na AWX a tím mít možnost automatizovat vzdálenou storage. Tato možnost bude implementována jako optional a nastavovaná pomoci ENV

**Comment by hates52** [comment]
Paramwters bude řešeno na úrovni StorageClass.

V _provisioner_, bude plugin ve tvaru _storage-operator.cfy.cz/<plugin>_
V _parameters_ budou uvedeny parametry potřebné pro daný plugin.

Příklad jak muže vypadat storageClass

```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
mountOptions:
- nfsvers=4
- hard
- intr
provisioner: storage-operator.cfy.cz/awx
parameters:
  hosts: "tvlsnfs01.pmb.cz"
  job-template-id: "105"
  volume-group: "vg_nfs"
reclaimPolicy: Retain
volumeBindingMode: Immediate
```

Secrets pro automatizační endpoint jsou předávány jako ENV pro kontejner.
Každý plugin muže vyžadovat jine ENV.
Například Ansible AWX bude používat: CLUSTER_NAME, AWX_URL, AWX_USERNAME, AWX_PASSWORD

Pokud nebude vyžadován automation, tak provisioner bude uveden jako _kubernetes.io/no-provisioner_
